### ISSUE TITLE
compiling issues

### ISSUE THREAD

**Issue by dafrasaga** [mypaint/libmypaint#114] opened 2018-01-29 15:10 UTC
Hi I'm trying to compile on Slackware-current but I have some issues; 

    make[2]: Entering directory '/root/git/libmypaint’
    depbase=echo mypaint-brush.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||';
    /bin/sh ./libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I/usr/local/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-brush.lo -MD -MP -MF $depbase.Tpo -c -o mypaint-brush.lo mypaint-brush.c &&
    mv -f $depbase.Tpo $depbase.Plo
    libtool: compile: gcc -DHAVE_CONFIG_H -I. -I/usr/local/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-brush.lo -MD -MP -MF .deps/mypaint-brush.Tpo -c mypaint-brush.c -fPIC -DPIC -o .libs/mypaint-brush.o
    mypaint-brush.c: In function ‘mypaint_brush_new’:
    mypaint-brush.c:133:26: error: ‘FALSE’ undeclared (first use in this function); did you mean ‘FILE’?
    self->print_inputs = FALSE;
    ^~~~~
    FILE
    mypaint-brush.c:133:26: note: each undeclared identifier is reported only once for each function it appears in
    mypaint-brush.c:142:29: error: ‘TRUE’ undeclared (first use in this function)
    self->reset_requested = TRUE;
    ^~~~
    mypaint-brush.c: In function ‘mypaint_brush_reset’:
    mypaint-brush.c:225:29: error: ‘TRUE’ undeclared (first use in this function)
    self->reset_requested = TRUE;
    ^~~~
    mypaint-brush.c: In function ‘mypaint_brush_stroke_to’:
    mypaint-brush.c:961:31: error: ‘FALSE’ undeclared (first use in this function); did you mean ‘FILE’?
    self->reset_requested = FALSE;
    ^~~~~
    FILE
    mypaint-brush.c:980:14: error: ‘TRUE’ undeclared (first use in this function)
    return TRUE;
    ^~~~
    mypaint-brush.c: In function ‘obj_get’:
    mypaint-brush.c:1100:44: error: ‘TRUE’ undeclared (first use in this function)
    && (obj_out ? (*obj_out != NULL) : TRUE);
    ^~~~
    mypaint-brush.c: In function ‘update_brush_setting_from_json_object’:
    mypaint-brush.c:1120:16: error: ‘FALSE’ undeclared (first use in this function); did you mean ‘FILE’?
    return FALSE;
    ^~~~~
    FILE
    mypaint-brush.c:1167:12: error: ‘TRUE’ undeclared (first use in this function)

    return TRUE;
    ^~~~
    mypaint-brush.c: In function ‘update_brush_from_json_object’:
    mypaint-brush.c:1177:16: error: ‘FALSE’ undeclared (first use in this function); did you mean ‘FILE’?
    return FALSE;
    ^~~~~
    FILE
    mypaint-brush.c:1193:28: error: ‘TRUE’ undeclared (first use in this function)
    gboolean updated_all = TRUE;
    ^~~~
    mypaint-brush.c: In function ‘mypaint_brush_from_string’:
    mypaint-brush.c:1227:16: error: ‘FALSE’ undeclared (first use in this function); did you mean ‘FILE’?
    return FALSE;
    ^~~~~
    FILE
    make[2]: *** [Makefile:730: mypaint-brush.lo] Error 1
    make[2]: Leaving directory '/root/git/libmypaint’
    make[1]: *** [Makefile:840: all-recursive] Error 1
    make[1]: Leaving directory '/root/git/libmypaint’
    make: *** [Makefile:598: all] Error 2

**Comment by jplloyd** [comment] 2019-12-27 13:17
@dafrasaga Since it's been almost two years, you probably resolved this. If not, this is either caused by not including the glib-2.0 headers correctly, or #undef'ing the TRUE/FALSE macros afterwards (which seems very strange).

If this is no longer an issue, you can ignore this and I'll close it on Monday.

**Closed** 2020-01-02 09:06 UTC

**Comment by ryandesign** [comment] 2020-06-02 21:12
Better late than never: I believe it was fixed by f4fd97445d3b6843af57ff8ba5f02cbdeb3942e9. See also https://trac.macports.org/ticket/60574 where we had the same problem reported to MacPorts.
